name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string

permissions: write-all

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout jtokkit repository'
        uses: actions/checkout@v4

      - name: Set up JDK 8 and JDK 21 with Gradle Cache
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: |
              8
              21
            cache: 'gradle'

      - name: Generate version
        run: |
          echo "EXPLYT_JTOKKIT_VERSION="${RELEASE_VERSION}"" >> $GITHUB_ENV

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :lib:build

      - name: Publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            :lib:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          VERSION: ${{ env.EXPLYT_JTOKKIT_VERSION }}
